Update bookkeeper and zookeeper
diennea/blobit pull request #49
Opened 2023-05-29 10:34 UTC by dmercuriali

updated 

- bookkeeper to 4.16.1
- zookeeper to 3.8.1
- netty to 4.1.92.Final

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

2023-05-30 08:28 UTC, diegosalvi requested changes

2023-05-30 08:28 UTC, diegosalvi commented on blobit-services/src/main/java/blobit/server/EmbeddedBookie.java
>          if (conf.isHttpServerEnabled()) {
This shouldn't be needed anymore. The EmdeddedServer already handle httpserver startup. See https://github.com/apache/bookkeeper/blob/575a81c79e90e256e919287ef9762bc14d15789a/bookkeeper-server/src/main/java/org/apache/bookkeeper/server/EmbeddedServer.java#L464

2023-05-30 10:09 UTC, eolivelli approved these changes
+1

2023-05-31 02:27 UTC, dmercuriali commented on blobit-services/src/main/java/blobit/server/EmbeddedBookie.java
>          if (conf.isHttpServerEnabled()) {
removed the httpserver init. Kept the log

2023-06-01 10:03 UTC, diegosalvi approved these changes

2023-06-01 10:03 UTC, merged